# Pelican — game-server control panel (https://pelican.dev).
#
# Two halves. The panel is the web UI and runs as a container; wings is the
# daemon that actually starts game servers, and it runs on the host because it
# drives the Docker socket directly.
#
# Deliberately imperative below the panel: games are installed, configured and
# updated through the web UI, and their files live in /var/lib/pelican rather
# than in this flake. Wings' own config is generated by the panel when a node is
# created and pasted into /etc/pelican/config.yml — it is runtime state, not
# something to declare here.
#
# SETUP, after the first rebuild:
#   1. browse to appUrl below -> run the installer, create the admin user
#   2. Admin -> Nodes -> Create Node; FQDN is this host's tailnet address,
#      daemon port 8080, sftp port 2022
#   3. paste the generated config into /etc/pelican/config.yml, then
#      systemctl restart pelican-wings
#   4. only then point appUrl at game.<domain> and add the vhost on the VPS
#
# Game ports are published by Docker, which installs its own DNAT rules ahead of
# the NixOS firewall — a published port is reachable from the LAN whether or not
# networking.firewall opens it. Public play still needs the VPS to relay the
# port across the tailnet.
{
  config,
  pkgs,
  ...
}: let
  panelPort = 8085;
  wingsPort = 8080;
  sftpPort = 2022;
  stateDir = "/var/lib/pelican";

  # The panel redirects everything to APP_URL, so it must match the address you
  # actually browse to. Caddy on the VPS fronts this hostname and forwards to
  # panelPort across the tailnet.
  appUrl = "https://game.${config.var.domain}";

  wings = pkgs.stdenvNoCC.mkDerivation rec {
    pname = "pelican-wings";
    version = "1.0.0-beta29";
    src = pkgs.fetchurl {
      url = "https://github.com/pelican-dev/wings/releases/download/v${version}/wings_linux_amd64";
      hash = "sha256-ddgezyU2btPAWtbGzLrVMu2Ja4IZqp0sk6WvAD1pAAs=";
    };
    dontUnpack = true;
    # Upstream ships a static Go binary, so there is nothing to patchelf.
    installPhase = "install -Dm755 $src $out/bin/wings";
  };
in {
  virtualisation.docker.enable = true;
  virtualisation.oci-containers.backend = "docker";

  # On PATH for `wings configure`, which writes the node config the panel
  # generates. The service itself runs the store path directly.
  environment.systemPackages = [wings];

  # wings owns game-server files as this user and, finding it absent, shells
  # out to useradd — which does not exist here, because NixOS declares users
  # rather than mutating /etc/passwd. Declaring it up front is the whole fix:
  # wings looks the name up first and only falls back to creating it.
  users.users.pelican = {
    isSystemUser = true;
    group = "pelican";
    home = stateDir;
  };
  users.groups.pelican = {};

  # Docker is only enabled here, for wings, so the group grant lives here too.
  users.users.${config.var.username}.extraGroups = ["docker"];

  # The panel image is php:8.5-fpm-alpine, where php-fpm drops to www-data
  # (uid/gid 82). The entrypoint runs as root but the worker does not, so the
  # bind-mounted dirs have to be owned by 82 or Laravel cannot write its log.
  systemd.tmpfiles.rules = [
    "d ${stateDir} 0755 root root - -"
    "d ${stateDir}/panel 0755 root root - -"
    "d ${stateDir}/panel/data 0750 82 82 - -"
    "d ${stateDir}/panel/logs 0750 82 82 - -"
    "d ${stateDir}/panel/plugins 0750 82 82 - -"
    # Z, not just d: the first run created files in these dirs as root before
    # the ownership above was right, and d only applies to the dir itself.
    "Z ${stateDir}/panel/data 0750 82 82 - -"
    "Z ${stateDir}/panel/logs 0750 82 82 - -"
    "Z ${stateDir}/panel/plugins 0750 82 82 - -"
    # Owned by the login user so the node config generated by the panel can be
    # pasted in without root; wings runs as root and reads it regardless.
    "d /etc/pelican 0750 ${config.var.username} root - -"
    "d /var/log/pelican 0700 root root - -"
  ];

  virtualisation.oci-containers.containers.pelican-panel = {
    image = "ghcr.io/pelican/panel:latest";
    autoStart = true;
    # Runs as the image's own www-data (82), not root. Upstream's bind-mount
    # compose forces 0:0 so its entrypoint can chown the mounts, but tmpfiles
    # above already owns them correctly. Running as root instead leaves .env
    # root-owned, and php-fpm — which is www-data — then cannot write the
    # installer's database settings back into it.
    ports = ["${toString panelPort}:80"];
    volumes = [
      "${stateDir}/panel/data:/pelican-data"
      "${stateDir}/panel/logs:/var/www/html/storage/logs"
      "${stateDir}/panel/plugins:/var/www/html/plugins"
    ];
    environment = {
      APP_URL = appUrl;
      APP_ENV = "production";
      APP_DEBUG = "false";
      XDG_DATA_HOME = "/pelican-data";
      # Caddy on the VPS terminates TLS and forwards over the tailnet, so the
      # panel must trust that hop to build correct absolute URLs.
      BEHIND_PROXY = "true";
      TRUSTED_PROXIES = "100.64.0.0/10";
    };
    extraOptions = ["--add-host=host.docker.internal:host-gateway"];
  };

  systemd.services.pelican-wings = {
    description = "Pelican wings — game server daemon";
    wantedBy = ["multi-user.target"];
    after = ["docker.service" "docker.socket" "network-online.target"];
    wants = ["network-online.target"];
    startLimitIntervalSec = 180;
    serviceConfig = {
      # Runs as root: it drives the Docker socket and chowns game files into
      # the per-server uids it allocates.
      User = "root";
      WorkingDirectory = "/etc/pelican";
      ExecStart = "${wings}/bin/wings --config /etc/pelican/config.yml";
      Restart = "on-failure";
      RestartSec = "5s";
    };
    # config.yml only exists once a node has been created in the panel. Without
    # this the unit fails on every rebuild until that is done, which makes
    # nixos-rebuild itself report failure.
    unitConfig.ConditionPathExists = "/etc/pelican/config.yml";
  };

  # config.yml only exists once a node is created in the panel, which is a
  # manual step in the web UI. Watching for it means wings comes up on its own
  # rather than needing a root systemctl start afterwards.
  systemd.paths.pelican-wings = {
    wantedBy = ["multi-user.target"];
    pathConfig = {
      PathExists = "/etc/pelican/config.yml";
      Unit = "pelican-wings.service";
    };
  };

  networking.firewall.interfaces.tailscale0.allowedTCPPorts = [
    panelPort
    wingsPort
    sftpPort
  ];
}
